### ISSUE TITLE
Error with courses 

### ISSUE THREAD

**Issue by rmartico** [ada1012/eLearningQA#3]
Running with any course on UBUVirtual, throws this error trace:

2023-05-25 11:18:35.863 ERROR 25348 --- [nio-8080-exec-2] o.a.jsp.WEB_002dINF.jsp.informe_jsp      : exception

java.lang.NumberFormatException: For input string: "0,00"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[na:1.8.0_361]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[na:1.8.0_361]
	at java.lang.Double.parseDouble(Double.java:538) ~[na:1.8.0_361]
	at es.ubu.lsi.WebServiceClient.obtenerEstadisticasNotasPregunta(WebServiceClient.java:919) ~[classes/:na]
	at es.ubu.lsi.ELearningQAFacade.generarGraficoPreguntas(ELearningQAFacade.java:232) ~[classes/:na]
	at org.apache.jsp.WEB_002dINF.jsp.informe_jsp._jspService(informe_jsp.java:199) ~[na:na]

**Comment by ada1012** [comment]
Try again with this changes: https://github.com/ada1012/eLearningQA/commit/f28a7fd59a8d88541fabe30ab225eb3b16cd1685

**Comment by rmartico** [comment]
Ok.
