### ISSUE TITLE
Error accesing course

### ISSUE THREAD

**Issue by rmartico** [ada1012/eLearningQA#5]
java.lang.NullPointerException: null
	at es.ubu.lsi.WebServiceClient.muestraCriterios(WebServiceClient.java:640) ~[classes/:na]
	at es.ubu.lsi.ELearningQAFacade.isMuestraCriterios(ELearningQAFacade.java:372) ~[classes/:na]
	at es.ubu.lsi.ELearningQAFacade.realizarComprobaciones(ELearningQAFacade.java:111) ~[classes/:na]
	at org.apache.jsp.WEB_002dINF.jsp.informe_jsp._jspService(informe_jsp.java:216) ~[na:na]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) [tomcat-embed-jasper-9.0.37.jar:9.0.37]

**Comment by ada1012** [comment]
I've added  nullsafety to that method so now it should work. Try again with this changes: https://github.com/ada1012/eLearningQA/commit/a11ce4b71f877d55fb5fee1e0774a9a619fea101
